// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: article/reason_enum.proto

package article

import (
	_ "github.com/go-kratos/kratos/v3/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_UNKNOWN                ErrorReason = 0
	ErrorReason_BAD_PARAM              ErrorReason = 40000
	ErrorReason_ARTICLE_NOT_FOUND      ErrorReason = 40400
	ErrorReason_SERVER_ERROR           ErrorReason = 50000
	ErrorReason_DB_ERROR               ErrorReason = 50001
	ErrorReason_TX_ERROR               ErrorReason = 50002
	ErrorReason_ARTICLE_CREATE_FAILURE ErrorReason = 50003
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:     "UNKNOWN",
		40000: "BAD_PARAM",
		40400: "ARTICLE_NOT_FOUND",
		50000: "SERVER_ERROR",
		50001: "DB_ERROR",
		50002: "TX_ERROR",
		50003: "ARTICLE_CREATE_FAILURE",
	}
	ErrorReason_value = map[string]int32{
		"UNKNOWN":                0,
		"BAD_PARAM":              40000,
		"ARTICLE_NOT_FOUND":      40400,
		"SERVER_ERROR":           50000,
		"DB_ERROR":               50001,
		"TX_ERROR":               50002,
		"ARTICLE_CREATE_FAILURE": 50003,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_article_reason_enum_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_article_reason_enum_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_article_reason_enum_proto_rawDescGZIP(), []int{0}
}

var File_article_reason_enum_proto protoreflect.FileDescriptor

const file_article_reason_enum_proto_rawDesc = "" +
	"\n" +
	"\x19article/reason_enum.proto\x12\aarticle\x1a\x13errors/errors.proto*\xc6\x01\n" +
	"\vErrorReason\x12\x11\n" +
	"\aUNKNOWN\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x15\n" +
	"\tBAD_PARAM\x10\xc0\xb8\x02\x1a\x04\xa8E\x90\x03\x12\x1d\n" +
	"\x11ARTICLE_NOT_FOUND\x10л\x02\x1a\x04\xa8E\x94\x03\x12\x18\n" +
	"\fSERVER_ERROR\x10І\x03\x1a\x04\xa8E\xf4\x03\x12\x14\n" +
	"\bDB_ERROR\x10ц\x03\x1a\x04\xa8E\xf4\x03\x12\x14\n" +
	"\bTX_ERROR\x10҆\x03\x1a\x04\xa8E\xf4\x03\x12\"\n" +
	"\x16ARTICLE_CREATE_FAILURE\x10ӆ\x03\x1a\x04\xa8E\xf4\x03\x1a\x04\xa0E\xf4\x03B!Z\x1fdemo2kratos/api/article;articleb\x06proto3"

var (
	file_article_reason_enum_proto_rawDescOnce sync.Once
	file_article_reason_enum_proto_rawDescData []byte
)

func file_article_reason_enum_proto_rawDescGZIP() []byte {
	file_article_reason_enum_proto_rawDescOnce.Do(func() {
		file_article_reason_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_article_reason_enum_proto_rawDesc), len(file_article_reason_enum_proto_rawDesc)))
	})
	return file_article_reason_enum_proto_rawDescData
}

var file_article_reason_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_article_reason_enum_proto_goTypes = []any{
	(ErrorReason)(0), // 0: article.ErrorReason
}
var file_article_reason_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_article_reason_enum_proto_init() }
func file_article_reason_enum_proto_init() {
	if File_article_reason_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_reason_enum_proto_rawDesc), len(file_article_reason_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_article_reason_enum_proto_goTypes,
		DependencyIndexes: file_article_reason_enum_proto_depIdxs,
		EnumInfos:         file_article_reason_enum_proto_enumTypes,
	}.Build()
	File_article_reason_enum_proto = out.File
	file_article_reason_enum_proto_goTypes = nil
	file_article_reason_enum_proto_depIdxs = nil
}
