// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/yylego/kratos-examples/demo1kratos/internal/biz"
	"github.com/yylego/kratos-examples/demo1kratos/internal/conf"
	"github.com/yylego/kratos-examples/demo1kratos/internal/data"
	"github.com/yylego/kratos-examples/demo1kratos/internal/server"
	"github.com/yylego/kratos-examples/demo1kratos/internal/service"
	"github.com/yylego/kratos-zapzh/zapzhkratos"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, t匝普日志 *zapzhkratos.T匝普日志) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, t匝普日志)
	if err != nil {
		return nil, nil, err
	}
	studentUsecase := biz.NewStudentUsecase(dataData, t匝普日志)
	studentService := service.NewStudentService(studentUsecase, t匝普日志)
	grpcServer := server.NewGRPCServer(confServer, studentService, t匝普日志)
	httpServer := server.NewHTTPServer(confServer, studentService, t匝普日志)
	app := newApp(grpcServer, httpServer, t匝普日志)
	return app, func() {
		cleanup()
	}, nil
}
