// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package student

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v3/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknown(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNKNOWN.String() && e.Code == 500
}

func ErrorUnknown(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UNKNOWN.String(), fmt.Sprintf(format, args...))
}

func IsBadParam(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_BAD_PARAM.String() && e.Code == 400
}

func ErrorBadParam(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_BAD_PARAM.String(), fmt.Sprintf(format, args...))
}

func IsStudentNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_STUDENT_NOT_FOUND.String() && e.Code == 404
}

func ErrorStudentNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_STUDENT_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsServerError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SERVER_ERROR.String() && e.Code == 500
}

func ErrorServerError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_SERVER_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsDbError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DB_ERROR.String() && e.Code == 500
}

func ErrorDbError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DB_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsTxError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TX_ERROR.String() && e.Code == 500
}

func ErrorTxError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_TX_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsStudentCreateFailure(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_STUDENT_CREATE_FAILURE.String() && e.Code == 500
}

func ErrorStudentCreateFailure(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_STUDENT_CREATE_FAILURE.String(), fmt.Sprintf(format, args...))
}
