// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: student/student.proto

package student

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	ClassName     string                 `protobuf:"bytes,4,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentInfo) Reset() {
	*x = StudentInfo{}
	mi := &file_student_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentInfo) ProtoMessage() {}

func (x *StudentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentInfo.ProtoReflect.Descriptor instead.
func (*StudentInfo) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{0}
}

func (x *StudentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *StudentInfo) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type CreateStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	ClassName     string                 `protobuf:"bytes,3,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentRequest) Reset() {
	*x = CreateStudentRequest{}
	mi := &file_student_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentRequest) ProtoMessage() {}

func (x *CreateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStudentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStudentRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateStudentRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type CreateStudentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *StudentInfo           `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentReply) Reset() {
	*x = CreateStudentReply{}
	mi := &file_student_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentReply) ProtoMessage() {}

func (x *CreateStudentReply) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentReply.ProtoReflect.Descriptor instead.
func (*CreateStudentReply) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStudentReply) GetStudent() *StudentInfo {
	if x != nil {
		return x.Student
	}
	return nil
}

type UpdateStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	ClassName     string                 `protobuf:"bytes,4,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentRequest) Reset() {
	*x = UpdateStudentRequest{}
	mi := &file_student_student_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentRequest) ProtoMessage() {}

func (x *UpdateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStudentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStudentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateStudentRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateStudentRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type UpdateStudentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *StudentInfo           `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentReply) Reset() {
	*x = UpdateStudentReply{}
	mi := &file_student_student_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentReply) ProtoMessage() {}

func (x *UpdateStudentReply) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentReply.ProtoReflect.Descriptor instead.
func (*UpdateStudentReply) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStudentReply) GetStudent() *StudentInfo {
	if x != nil {
		return x.Student
	}
	return nil
}

type DeleteStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentRequest) Reset() {
	*x = DeleteStudentRequest{}
	mi := &file_student_student_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentRequest) ProtoMessage() {}

func (x *DeleteStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentRequest.ProtoReflect.Descriptor instead.
func (*DeleteStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteStudentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteStudentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudentReply) Reset() {
	*x = DeleteStudentReply{}
	mi := &file_student_student_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudentReply) ProtoMessage() {}

func (x *DeleteStudentReply) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudentReply.ProtoReflect.Descriptor instead.
func (*DeleteStudentReply) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteStudentReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentRequest) Reset() {
	*x = GetStudentRequest{}
	mi := &file_student_student_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentRequest) ProtoMessage() {}

func (x *GetStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentRequest.ProtoReflect.Descriptor instead.
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{7}
}

func (x *GetStudentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStudentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *StudentInfo           `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentReply) Reset() {
	*x = GetStudentReply{}
	mi := &file_student_student_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentReply) ProtoMessage() {}

func (x *GetStudentReply) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentReply.ProtoReflect.Descriptor instead.
func (*GetStudentReply) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{8}
}

func (x *GetStudentReply) GetStudent() *StudentInfo {
	if x != nil {
		return x.Student
	}
	return nil
}

type ListStudentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentsRequest) Reset() {
	*x = ListStudentsRequest{}
	mi := &file_student_student_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentsRequest) ProtoMessage() {}

func (x *ListStudentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentsRequest.ProtoReflect.Descriptor instead.
func (*ListStudentsRequest) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{9}
}

func (x *ListStudentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListStudentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListStudentsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*StudentInfo         `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentsReply) Reset() {
	*x = ListStudentsReply{}
	mi := &file_student_student_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentsReply) ProtoMessage() {}

func (x *ListStudentsReply) ProtoReflect() protoreflect.Message {
	mi := &file_student_student_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentsReply.ProtoReflect.Descriptor instead.
func (*ListStudentsReply) Descriptor() ([]byte, []int) {
	return file_student_student_proto_rawDescGZIP(), []int{10}
}

func (x *ListStudentsReply) GetStudents() []*StudentInfo {
	if x != nil {
		return x.Students
	}
	return nil
}

func (x *ListStudentsReply) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_student_student_proto protoreflect.FileDescriptor

const file_student_student_proto_rawDesc = "" +
	"\n" +
	"\x15student/student.proto\x12\astudent\x1a\x1cgoogle/api/annotations.proto\"b\n" +
	"\vStudentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x1d\n" +
	"\n" +
	"class_name\x18\x04 \x01(\tR\tclassName\"[\n" +
	"\x14CreateStudentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x1d\n" +
	"\n" +
	"class_name\x18\x03 \x01(\tR\tclassName\"D\n" +
	"\x12CreateStudentReply\x12.\n" +
	"\astudent\x18\x01 \x01(\v2\x14.student.StudentInfoR\astudent\"k\n" +
	"\x14UpdateStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x1d\n" +
	"\n" +
	"class_name\x18\x04 \x01(\tR\tclassName\"D\n" +
	"\x12UpdateStudentReply\x12.\n" +
	"\astudent\x18\x01 \x01(\v2\x14.student.StudentInfoR\astudent\"&\n" +
	"\x14DeleteStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\".\n" +
	"\x12DeleteStudentReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11GetStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"A\n" +
	"\x0fGetStudentReply\x12.\n" +
	"\astudent\x18\x01 \x01(\v2\x14.student.StudentInfoR\astudent\"F\n" +
	"\x13ListStudentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"[\n" +
	"\x11ListStudentsReply\x120\n" +
	"\bstudents\x18\x01 \x03(\v2\x14.student.StudentInfoR\bstudents\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xf9\x03\n" +
	"\x0eStudentService\x12a\n" +
	"\rCreateStudent\x12\x1d.student.CreateStudentRequest\x1a\x1b.student.CreateStudentReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/students\x12f\n" +
	"\rUpdateStudent\x12\x1d.student.UpdateStudentRequest\x1a\x1b.student.UpdateStudentReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/students/{id}\x12c\n" +
	"\rDeleteStudent\x12\x1d.student.DeleteStudentRequest\x1a\x1b.student.DeleteStudentReply\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/students/{id}\x12Z\n" +
	"\n" +
	"GetStudent\x12\x1a.student.GetStudentRequest\x1a\x18.student.GetStudentReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/students/{id}\x12[\n" +
	"\fListStudents\x12\x1c.student.ListStudentsRequest\x1a\x1a.student.ListStudentsReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/studentsB!Z\x1fdemo1kratos/api/student;studentb\x06proto3"

var (
	file_student_student_proto_rawDescOnce sync.Once
	file_student_student_proto_rawDescData []byte
)

func file_student_student_proto_rawDescGZIP() []byte {
	file_student_student_proto_rawDescOnce.Do(func() {
		file_student_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_student_student_proto_rawDesc), len(file_student_student_proto_rawDesc)))
	})
	return file_student_student_proto_rawDescData
}

var file_student_student_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_student_student_proto_goTypes = []any{
	(*StudentInfo)(nil),          // 0: student.StudentInfo
	(*CreateStudentRequest)(nil), // 1: student.CreateStudentRequest
	(*CreateStudentReply)(nil),   // 2: student.CreateStudentReply
	(*UpdateStudentRequest)(nil), // 3: student.UpdateStudentRequest
	(*UpdateStudentReply)(nil),   // 4: student.UpdateStudentReply
	(*DeleteStudentRequest)(nil), // 5: student.DeleteStudentRequest
	(*DeleteStudentReply)(nil),   // 6: student.DeleteStudentReply
	(*GetStudentRequest)(nil),    // 7: student.GetStudentRequest
	(*GetStudentReply)(nil),      // 8: student.GetStudentReply
	(*ListStudentsRequest)(nil),  // 9: student.ListStudentsRequest
	(*ListStudentsReply)(nil),    // 10: student.ListStudentsReply
}
var file_student_student_proto_depIdxs = []int32{
	0,  // 0: student.CreateStudentReply.student:type_name -> student.StudentInfo
	0,  // 1: student.UpdateStudentReply.student:type_name -> student.StudentInfo
	0,  // 2: student.GetStudentReply.student:type_name -> student.StudentInfo
	0,  // 3: student.ListStudentsReply.students:type_name -> student.StudentInfo
	1,  // 4: student.StudentService.CreateStudent:input_type -> student.CreateStudentRequest
	3,  // 5: student.StudentService.UpdateStudent:input_type -> student.UpdateStudentRequest
	5,  // 6: student.StudentService.DeleteStudent:input_type -> student.DeleteStudentRequest
	7,  // 7: student.StudentService.GetStudent:input_type -> student.GetStudentRequest
	9,  // 8: student.StudentService.ListStudents:input_type -> student.ListStudentsRequest
	2,  // 9: student.StudentService.CreateStudent:output_type -> student.CreateStudentReply
	4,  // 10: student.StudentService.UpdateStudent:output_type -> student.UpdateStudentReply
	6,  // 11: student.StudentService.DeleteStudent:output_type -> student.DeleteStudentReply
	8,  // 12: student.StudentService.GetStudent:output_type -> student.GetStudentReply
	10, // 13: student.StudentService.ListStudents:output_type -> student.ListStudentsReply
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_student_student_proto_init() }
func file_student_student_proto_init() {
	if File_student_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_student_student_proto_rawDesc), len(file_student_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_student_student_proto_goTypes,
		DependencyIndexes: file_student_student_proto_depIdxs,
		MessageInfos:      file_student_student_proto_msgTypes,
	}.Build()
	File_student_student_proto = out.File
	file_student_student_proto_goTypes = nil
	file_student_student_proto_depIdxs = nil
}
