server:
  http:
    address: 0.0.0.0:8001
    timeout: 1s
  grpc:
    address: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: postgres
    source: host=localhost port=5432 user=postgres password=123 dbname=kratos_examples_db sslmode=disable
